# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-28 08:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180727_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 28, 8, 13, 21, 916925, tzinfo=utc)),
        ),
    ]
