# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-28 08:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180728_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 28, 8, 19, 56, 537323, tzinfo=utc)),
        ),
    ]
