# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-30 15:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20180728_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 30, 15, 29, 27, 381375, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='articlecolumn',
            name='user',
        ),
        migrations.AddField(
            model_name='articlecolumn',
            name='user',
            field=models.ManyToManyField(related_name='article_column', to=settings.AUTH_USER_MODEL),
        ),
    ]
