# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-29 08:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20180730_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('c_date', models.DateTimeField(default=datetime.datetime(2018, 8, 29, 8, 7, 48, 711605, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='num_good',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='num_read',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 8, 7, 48, 707493, tzinfo=utc)),
        ),
    ]
