# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-08-29 11:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180829_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterField(
            model_name='article',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 11, 29, 20, 382283, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 29, 11, 29, 20, 384004, tzinfo=utc)),
        ),
        migrations.AlterIndexTogether(
            name='article',
            index_together=set([]),
        ),
    ]
